// Shared markdown -> HTML converter. Used by scripts/queue-article.cjs so a
// human (or VA) pasting markdown never lets raw markdown syntax reach
// data/blog/posts.json. Articles generated by Claude Code should be written
// as HTML directly and never need this, but it exists so nothing slips
// through as raw markdown.
function escapeHtml(s) {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

function inline(text) {
  let t = text;
  t = t.replace(/\[([^\]]+)\]\(([^)]+)\)/g, (_m, label, href) => {
    const external = /^https?:\/\//.test(href);
    const rel = external ? ' rel="noopener"' : "";
    const target = external ? ' target="_blank"' : "";
    return `<a href="${href}"${rel}${target}>${label}</a>`;
  });
  t = t.replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>");
  t = t.replace(/(?<!\*)\*([^*]+)\*(?!\*)/g, "<em>$1</em>");
  return t;
}

function mdToHtml(md) {
  const lines = md.replace(/\r\n/g, "\n").split("\n");
  const out = [];
  let i = 0;
  let listBuffer = [];
  let listType = null;

  function flushList() {
    if (listBuffer.length) {
      out.push(`<${listType}>${listBuffer.map((li) => `<li>${inline(li)}</li>`).join("")}</${listType}>`);
      listBuffer = [];
      listType = null;
    }
  }

  while (i < lines.length) {
    const line = lines[i];

    if (/^\s*$/.test(line)) {
      flushList();
      i++;
      continue;
    }

    const h = line.match(/^(#{1,4})\s+(.*)$/);
    if (h) {
      flushList();
      const level = h[1].length + 1; // markdown h1 -> html h2 (article already has its own h1)
      out.push(`<h${Math.min(level, 4)}>${inline(h[2])}</h${Math.min(level, 4)}>`);
      i++;
      continue;
    }

    const ol = line.match(/^\s*\d+\.\s+(.*)$/);
    if (ol) {
      if (listType !== "ol") flushList();
      listType = "ol";
      listBuffer.push(ol[1]);
      i++;
      continue;
    }

    const ul = line.match(/^\s*[-*]\s+(.*)$/);
    if (ul) {
      if (listType !== "ul") flushList();
      listType = "ul";
      listBuffer.push(ul[1]);
      i++;
      continue;
    }

    const bq = line.match(/^>\s?(.*)$/);
    if (bq) {
      flushList();
      out.push(`<blockquote><p>${inline(bq[1])}</p></blockquote>`);
      i++;
      continue;
    }

    flushList();
    out.push(`<p>${inline(line)}</p>`);
    i++;
  }
  flushList();
  return out.join("\n");
}

module.exports = { mdToHtml, escapeHtml, inline };
